package com.reco.generate.repository;

import com.reco.generate.entity.UiPub;
import com.reco.generate.entity.UiPubExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UiPubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    long countByExample(UiPubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    int deleteByExample(UiPubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    int insert(UiPub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    int insertSelective(UiPub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    List<UiPub> selectByExample(UiPubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    int updateByExampleSelective(@Param("record") UiPub record, @Param("example") UiPubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    int updateByExample(@Param("record") UiPub record, @Param("example") UiPubExample example);
}