package com.reco.generate.repository;

import com.reco.generate.core.BaseDao;
import com.reco.generate.entity.Report;
import com.reco.generate.entity.UserPayVal;
import com.reco.generate.entity.UserPayValExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPayValMapper extends BaseDao<UserPayVal, Integer, UserPayValExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int countByExample(UserPayValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int deleteByExample(UserPayValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int insert(UserPayVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int insertSelective(UserPayVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    List<UserPayVal> selectByExample(UserPayValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    UserPayVal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPayVal record, @Param("example") UserPayValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int updateByExample(@Param("record") UserPayVal record, @Param("example") UserPayValExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int updateByPrimaryKeySelective(UserPayVal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_val
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    int updateByPrimaryKey(UserPayVal record);

    Integer countByDate(@Param("startDate") String startDate, @Param("endDate") String endDate);

    Integer countBeforeDate(@Param("date") String date);

    List<Report> dailyCount(@Param("startDate") String startDate, @Param("endDate") String endDate);
}