package com.reco.generate.repository;

import com.reco.generate.bo.PurchaseRecordBo;
import com.reco.generate.core.BaseDao;
import com.reco.generate.entity.UserPayHistory;
import com.reco.generate.entity.UserPayHistoryExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserPayHistoryMapper extends BaseDao<UserPayHistory, Integer, UserPayHistoryExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int countByExample(UserPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int deleteByExample(UserPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int insert(UserPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int insertSelective(UserPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    List<UserPayHistory> selectByExample(UserPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    UserPayHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPayHistory record, @Param("example") UserPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int updateByExample(@Param("record") UserPayHistory record, @Param("example") UserPayHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int updateByPrimaryKeySelective(UserPayHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_history
     *
     * @mbg.generated Fri May 10 17:17:16 CST 2019
     */
    int updateByPrimaryKey(UserPayHistory record);

    List<PurchaseRecordBo> findBySongIds(@Param("songIdList") List<Integer> songIdList, @Param("from") Date from, @Param("to") Date to);
}