package com.reco.generate.entity;

import com.reco.generate.core.easyui.Datagrid;

import java.util.Date;

public class Activity extends Datagrid {

    private String createTime;

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.url
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.ctype
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer csort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.socnew
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String socnew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.pos
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.cline
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer cline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.ctime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.url
     *
     * @return the value of activity.url
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.url
     *
     * @param url the value for activity.url
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.cname
     *
     * @return the value of activity.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.cname
     *
     * @param cname the value for activity.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.pic
     *
     * @return the value of activity.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.pic
     *
     * @param pic the value for activity.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.ctype
     *
     * @return the value of activity.ctype
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.ctype
     *
     * @param ctype the value for activity.ctype
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.csort
     *
     * @return the value of activity.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCsort() {
        return csort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.csort
     *
     * @param csort the value for activity.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCsort(Integer csort) {
        this.csort = csort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.socnew
     *
     * @return the value of activity.socnew
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getSocnew() {
        return socnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.socnew
     *
     * @param socnew the value for activity.socnew
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setSocnew(String socnew) {
        this.socnew = socnew == null ? null : socnew.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.pos
     *
     * @return the value of activity.pos
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.pos
     *
     * @param pos the value for activity.pos
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.cline
     *
     * @return the value of activity.cline
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCline() {
        return cline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.cline
     *
     * @param cline the value for activity.cline
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCline(Integer cline) {
        this.cline = cline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.ctime
     *
     * @return the value of activity.ctime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.ctime
     *
     * @param ctime the value for activity.ctime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}