package com.reco.generate.entity;

import java.util.Date;

public class SongMp3 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.resid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String resid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.cname_len
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer cnameLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.abbr
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String abbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.id_artist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer idArtist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.cartist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String cartist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.carea
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String carea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.clanguage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer clanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.company
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.cage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer cage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer csort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.dtime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Date dtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_mp3.ctag
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String ctag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.id
     *
     * @return the value of song_mp3.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.id
     *
     * @param id the value for song_mp3.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.resid
     *
     * @return the value of song_mp3.resid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.resid
     *
     * @param resid the value for song_mp3.resid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setResid(String resid) {
        this.resid = resid == null ? null : resid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.cname
     *
     * @return the value of song_mp3.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.cname
     *
     * @param cname the value for song_mp3.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.cname_len
     *
     * @return the value of song_mp3.cname_len
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCnameLen() {
        return cnameLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.cname_len
     *
     * @param cnameLen the value for song_mp3.cname_len
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCnameLen(Integer cnameLen) {
        this.cnameLen = cnameLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.abbr
     *
     * @return the value of song_mp3.abbr
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.abbr
     *
     * @param abbr the value for song_mp3.abbr
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setAbbr(String abbr) {
        this.abbr = abbr == null ? null : abbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.id_artist
     *
     * @return the value of song_mp3.id_artist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getIdArtist() {
        return idArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.id_artist
     *
     * @param idArtist the value for song_mp3.id_artist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setIdArtist(Integer idArtist) {
        this.idArtist = idArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.cartist
     *
     * @return the value of song_mp3.cartist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCartist() {
        return cartist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.cartist
     *
     * @param cartist the value for song_mp3.cartist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCartist(String cartist) {
        this.cartist = cartist == null ? null : cartist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.carea
     *
     * @return the value of song_mp3.carea
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCarea() {
        return carea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.carea
     *
     * @param carea the value for song_mp3.carea
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCarea(String carea) {
        this.carea = carea == null ? null : carea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.clanguage
     *
     * @return the value of song_mp3.clanguage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getClanguage() {
        return clanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.clanguage
     *
     * @param clanguage the value for song_mp3.clanguage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setClanguage(Integer clanguage) {
        this.clanguage = clanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.company
     *
     * @return the value of song_mp3.company
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.company
     *
     * @param company the value for song_mp3.company
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.cage
     *
     * @return the value of song_mp3.cage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCage() {
        return cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.cage
     *
     * @param cage the value for song_mp3.cage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCage(Integer cage) {
        this.cage = cage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.pic
     *
     * @return the value of song_mp3.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.pic
     *
     * @param pic the value for song_mp3.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.csort
     *
     * @return the value of song_mp3.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCsort() {
        return csort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.csort
     *
     * @param csort the value for song_mp3.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCsort(Integer csort) {
        this.csort = csort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.dtime
     *
     * @return the value of song_mp3.dtime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.dtime
     *
     * @param dtime the value for song_mp3.dtime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_mp3.ctag
     *
     * @return the value of song_mp3.ctag
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCtag() {
        return ctag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_mp3.ctag
     *
     * @param ctag the value for song_mp3.ctag
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCtag(String ctag) {
        this.ctag = ctag == null ? null : ctag.trim();
    }
}