package com.reco.generate.entity;

import com.reco.generate.core.easyui.Datagrid;

import java.util.Date;

public class Song extends Datagrid {

    private String ids;

    public String getIds() {
        return ids;
    }

    public void setIds(String ids) {
        this.ids = ids;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.resid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String resid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.cname_len
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer cnameLen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.abbr
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String abbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.id_artist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer idArtist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.cartist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String cartist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.vtype
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer vtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.clanguage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer clanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer csort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.cline
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer cline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.dtime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Date dtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.id
     *
     * @return the value of song.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.id
     *
     * @param id the value for song.id
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.resid
     *
     * @return the value of song.resid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.resid
     *
     * @param resid the value for song.resid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setResid(String resid) {
        this.resid = resid == null ? null : resid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.cname
     *
     * @return the value of song.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.cname
     *
     * @param cname the value for song.cname
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.cname_len
     *
     * @return the value of song.cname_len
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCnameLen() {
        return cnameLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.cname_len
     *
     * @param cnameLen the value for song.cname_len
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCnameLen(Integer cnameLen) {
        this.cnameLen = cnameLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.abbr
     *
     * @return the value of song.abbr
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.abbr
     *
     * @param abbr the value for song.abbr
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setAbbr(String abbr) {
        this.abbr = abbr == null ? null : abbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.id_artist
     *
     * @return the value of song.id_artist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getIdArtist() {
        return idArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.id_artist
     *
     * @param idArtist the value for song.id_artist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setIdArtist(Integer idArtist) {
        this.idArtist = idArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.cartist
     *
     * @return the value of song.cartist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCartist() {
        return cartist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.cartist
     *
     * @param cartist the value for song.cartist
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCartist(String cartist) {
        this.cartist = cartist == null ? null : cartist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.vtype
     *
     * @return the value of song.vtype
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getVtype() {
        return vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.vtype
     *
     * @param vtype the value for song.vtype
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setVtype(Integer vtype) {
        this.vtype = vtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.clanguage
     *
     * @return the value of song.clanguage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getClanguage() {
        return clanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.clanguage
     *
     * @param clanguage the value for song.clanguage
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setClanguage(Integer clanguage) {
        this.clanguage = clanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.pic
     *
     * @return the value of song.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.pic
     *
     * @param pic the value for song.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.csort
     *
     * @return the value of song.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCsort() {
        return csort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.csort
     *
     * @param csort the value for song.csort
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCsort(Integer csort) {
        this.csort = csort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.cline
     *
     * @return the value of song.cline
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCline() {
        return cline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.cline
     *
     * @param cline the value for song.cline
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCline(Integer cline) {
        this.cline = cline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.dtime
     *
     * @return the value of song.dtime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.dtime
     *
     * @param dtime the value for song.dtime
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }
}