package com.reco.generate.entity;

import com.reco.generate.core.easyui.Datagrid;

public class UiPub extends Datagrid {

    private Integer activityId;

    private String cname;

    public Integer getActivityId() {
        return activityId;
    }

    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    public String getCname() {
        return cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.pid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.nid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer nid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.zindex
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer zindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.x
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.y
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.w
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer w;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.h
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.w2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer w2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.h2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer h2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.cfocus
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String cfocus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.cback
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer cback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.onclick_type
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private Integer onclickType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.curl
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String curl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.p1
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String p1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.p2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String p2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub.p3
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    private String p3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.pid
     *
     * @return the value of ui_pub.pid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.pid
     *
     * @param pid the value for ui_pub.pid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.nid
     *
     * @return the value of ui_pub.nid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.nid
     *
     * @param nid the value for ui_pub.nid
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.zindex
     *
     * @return the value of ui_pub.zindex
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getZindex() {
        return zindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.zindex
     *
     * @param zindex the value for ui_pub.zindex
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setZindex(Integer zindex) {
        this.zindex = zindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.x
     *
     * @return the value of ui_pub.x
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.x
     *
     * @param x the value for ui_pub.x
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.y
     *
     * @return the value of ui_pub.y
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.y
     *
     * @param y the value for ui_pub.y
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.w
     *
     * @return the value of ui_pub.w
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getW() {
        return w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.w
     *
     * @param w the value for ui_pub.w
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setW(Integer w) {
        this.w = w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.h
     *
     * @return the value of ui_pub.h
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getH() {
        return h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.h
     *
     * @param h the value for ui_pub.h
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setH(Integer h) {
        this.h = h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.w2
     *
     * @return the value of ui_pub.w2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getW2() {
        return w2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.w2
     *
     * @param w2 the value for ui_pub.w2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setW2(Integer w2) {
        this.w2 = w2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.h2
     *
     * @return the value of ui_pub.h2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getH2() {
        return h2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.h2
     *
     * @param h2 the value for ui_pub.h2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setH2(Integer h2) {
        this.h2 = h2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.cfocus
     *
     * @return the value of ui_pub.cfocus
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCfocus() {
        return cfocus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.cfocus
     *
     * @param cfocus the value for ui_pub.cfocus
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCfocus(String cfocus) {
        this.cfocus = cfocus == null ? null : cfocus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.pic
     *
     * @return the value of ui_pub.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.pic
     *
     * @param pic the value for ui_pub.pic
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.cback
     *
     * @return the value of ui_pub.cback
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getCback() {
        return cback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.cback
     *
     * @param cback the value for ui_pub.cback
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCback(Integer cback) {
        this.cback = cback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.onclick_type
     *
     * @return the value of ui_pub.onclick_type
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Integer getOnclickType() {
        return onclickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.onclick_type
     *
     * @param onclickType the value for ui_pub.onclick_type
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setOnclickType(Integer onclickType) {
        this.onclickType = onclickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.curl
     *
     * @return the value of ui_pub.curl
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.curl
     *
     * @param curl the value for ui_pub.curl
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.p1
     *
     * @return the value of ui_pub.p1
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getP1() {
        return p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.p1
     *
     * @param p1 the value for ui_pub.p1
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setP1(String p1) {
        this.p1 = p1 == null ? null : p1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.p2
     *
     * @return the value of ui_pub.p2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getP2() {
        return p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.p2
     *
     * @param p2 the value for ui_pub.p2
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setP2(String p2) {
        this.p2 = p2 == null ? null : p2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub.p3
     *
     * @return the value of ui_pub.p3
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getP3() {
        return p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub.p3
     *
     * @param p3 the value for ui_pub.p3
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setP3(String p3) {
        this.p3 = p3 == null ? null : p3.trim();
    }
}