package com.reco.generate.entity;

import com.reco.generate.core.easyui.Datagrid;

public class UiPubEnter extends Datagrid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.pos
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private Integer pos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.x
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.y
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.w
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private Integer w;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.h
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private Integer h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.curl
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private String curl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.ckey
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private String ckey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ui_pub_enter.pic
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.pos
     *
     * @return the value of ui_pub_enter.pos
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.pos
     *
     * @param pos the value for ui_pub_enter.pos
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setPos(Integer pos) {
        this.pos = pos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.x
     *
     * @return the value of ui_pub_enter.x
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.x
     *
     * @param x the value for ui_pub_enter.x
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.y
     *
     * @return the value of ui_pub_enter.y
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.y
     *
     * @param y the value for ui_pub_enter.y
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.w
     *
     * @return the value of ui_pub_enter.w
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public Integer getW() {
        return w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.w
     *
     * @param w the value for ui_pub_enter.w
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setW(Integer w) {
        this.w = w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.h
     *
     * @return the value of ui_pub_enter.h
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public Integer getH() {
        return h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.h
     *
     * @param h the value for ui_pub_enter.h
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setH(Integer h) {
        this.h = h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.curl
     *
     * @return the value of ui_pub_enter.curl
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.curl
     *
     * @param curl the value for ui_pub_enter.curl
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.ckey
     *
     * @return the value of ui_pub_enter.ckey
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public String getCkey() {
        return ckey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.ckey
     *
     * @param ckey the value for ui_pub_enter.ckey
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setCkey(String ckey) {
        this.ckey = ckey == null ? null : ckey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ui_pub_enter.pic
     *
     * @return the value of ui_pub_enter.pic
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ui_pub_enter.pic
     *
     * @param pic the value for ui_pub_enter.pic
     *
     * @mbg.generated Mon May 20 18:37:09 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }
}