package com.reco.generate.entity;

import java.util.ArrayList;
import java.util.List;

public class UiPubExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public UiPubExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andNidIsNull() {
            addCriterion("nid is null");
            return (Criteria) this;
        }

        public Criteria andNidIsNotNull() {
            addCriterion("nid is not null");
            return (Criteria) this;
        }

        public Criteria andNidEqualTo(Integer value) {
            addCriterion("nid =", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotEqualTo(Integer value) {
            addCriterion("nid <>", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidGreaterThan(Integer value) {
            addCriterion("nid >", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidGreaterThanOrEqualTo(Integer value) {
            addCriterion("nid >=", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidLessThan(Integer value) {
            addCriterion("nid <", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidLessThanOrEqualTo(Integer value) {
            addCriterion("nid <=", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidIn(List<Integer> values) {
            addCriterion("nid in", values, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotIn(List<Integer> values) {
            addCriterion("nid not in", values, "nid");
            return (Criteria) this;
        }

        public Criteria andNidBetween(Integer value1, Integer value2) {
            addCriterion("nid between", value1, value2, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotBetween(Integer value1, Integer value2) {
            addCriterion("nid not between", value1, value2, "nid");
            return (Criteria) this;
        }

        public Criteria andZindexIsNull() {
            addCriterion("zindex is null");
            return (Criteria) this;
        }

        public Criteria andZindexIsNotNull() {
            addCriterion("zindex is not null");
            return (Criteria) this;
        }

        public Criteria andZindexEqualTo(Integer value) {
            addCriterion("zindex =", value, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexNotEqualTo(Integer value) {
            addCriterion("zindex <>", value, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexGreaterThan(Integer value) {
            addCriterion("zindex >", value, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("zindex >=", value, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexLessThan(Integer value) {
            addCriterion("zindex <", value, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexLessThanOrEqualTo(Integer value) {
            addCriterion("zindex <=", value, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexIn(List<Integer> values) {
            addCriterion("zindex in", values, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexNotIn(List<Integer> values) {
            addCriterion("zindex not in", values, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexBetween(Integer value1, Integer value2) {
            addCriterion("zindex between", value1, value2, "zindex");
            return (Criteria) this;
        }

        public Criteria andZindexNotBetween(Integer value1, Integer value2) {
            addCriterion("zindex not between", value1, value2, "zindex");
            return (Criteria) this;
        }

        public Criteria andXIsNull() {
            addCriterion("x is null");
            return (Criteria) this;
        }

        public Criteria andXIsNotNull() {
            addCriterion("x is not null");
            return (Criteria) this;
        }

        public Criteria andXEqualTo(Integer value) {
            addCriterion("x =", value, "x");
            return (Criteria) this;
        }

        public Criteria andXNotEqualTo(Integer value) {
            addCriterion("x <>", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThan(Integer value) {
            addCriterion("x >", value, "x");
            return (Criteria) this;
        }

        public Criteria andXGreaterThanOrEqualTo(Integer value) {
            addCriterion("x >=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThan(Integer value) {
            addCriterion("x <", value, "x");
            return (Criteria) this;
        }

        public Criteria andXLessThanOrEqualTo(Integer value) {
            addCriterion("x <=", value, "x");
            return (Criteria) this;
        }

        public Criteria andXIn(List<Integer> values) {
            addCriterion("x in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXNotIn(List<Integer> values) {
            addCriterion("x not in", values, "x");
            return (Criteria) this;
        }

        public Criteria andXBetween(Integer value1, Integer value2) {
            addCriterion("x between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andXNotBetween(Integer value1, Integer value2) {
            addCriterion("x not between", value1, value2, "x");
            return (Criteria) this;
        }

        public Criteria andYIsNull() {
            addCriterion("y is null");
            return (Criteria) this;
        }

        public Criteria andYIsNotNull() {
            addCriterion("y is not null");
            return (Criteria) this;
        }

        public Criteria andYEqualTo(Integer value) {
            addCriterion("y =", value, "y");
            return (Criteria) this;
        }

        public Criteria andYNotEqualTo(Integer value) {
            addCriterion("y <>", value, "y");
            return (Criteria) this;
        }

        public Criteria andYGreaterThan(Integer value) {
            addCriterion("y >", value, "y");
            return (Criteria) this;
        }

        public Criteria andYGreaterThanOrEqualTo(Integer value) {
            addCriterion("y >=", value, "y");
            return (Criteria) this;
        }

        public Criteria andYLessThan(Integer value) {
            addCriterion("y <", value, "y");
            return (Criteria) this;
        }

        public Criteria andYLessThanOrEqualTo(Integer value) {
            addCriterion("y <=", value, "y");
            return (Criteria) this;
        }

        public Criteria andYIn(List<Integer> values) {
            addCriterion("y in", values, "y");
            return (Criteria) this;
        }

        public Criteria andYNotIn(List<Integer> values) {
            addCriterion("y not in", values, "y");
            return (Criteria) this;
        }

        public Criteria andYBetween(Integer value1, Integer value2) {
            addCriterion("y between", value1, value2, "y");
            return (Criteria) this;
        }

        public Criteria andYNotBetween(Integer value1, Integer value2) {
            addCriterion("y not between", value1, value2, "y");
            return (Criteria) this;
        }

        public Criteria andWIsNull() {
            addCriterion("w is null");
            return (Criteria) this;
        }

        public Criteria andWIsNotNull() {
            addCriterion("w is not null");
            return (Criteria) this;
        }

        public Criteria andWEqualTo(Integer value) {
            addCriterion("w =", value, "w");
            return (Criteria) this;
        }

        public Criteria andWNotEqualTo(Integer value) {
            addCriterion("w <>", value, "w");
            return (Criteria) this;
        }

        public Criteria andWGreaterThan(Integer value) {
            addCriterion("w >", value, "w");
            return (Criteria) this;
        }

        public Criteria andWGreaterThanOrEqualTo(Integer value) {
            addCriterion("w >=", value, "w");
            return (Criteria) this;
        }

        public Criteria andWLessThan(Integer value) {
            addCriterion("w <", value, "w");
            return (Criteria) this;
        }

        public Criteria andWLessThanOrEqualTo(Integer value) {
            addCriterion("w <=", value, "w");
            return (Criteria) this;
        }

        public Criteria andWIn(List<Integer> values) {
            addCriterion("w in", values, "w");
            return (Criteria) this;
        }

        public Criteria andWNotIn(List<Integer> values) {
            addCriterion("w not in", values, "w");
            return (Criteria) this;
        }

        public Criteria andWBetween(Integer value1, Integer value2) {
            addCriterion("w between", value1, value2, "w");
            return (Criteria) this;
        }

        public Criteria andWNotBetween(Integer value1, Integer value2) {
            addCriterion("w not between", value1, value2, "w");
            return (Criteria) this;
        }

        public Criteria andHIsNull() {
            addCriterion("h is null");
            return (Criteria) this;
        }

        public Criteria andHIsNotNull() {
            addCriterion("h is not null");
            return (Criteria) this;
        }

        public Criteria andHEqualTo(Integer value) {
            addCriterion("h =", value, "h");
            return (Criteria) this;
        }

        public Criteria andHNotEqualTo(Integer value) {
            addCriterion("h <>", value, "h");
            return (Criteria) this;
        }

        public Criteria andHGreaterThan(Integer value) {
            addCriterion("h >", value, "h");
            return (Criteria) this;
        }

        public Criteria andHGreaterThanOrEqualTo(Integer value) {
            addCriterion("h >=", value, "h");
            return (Criteria) this;
        }

        public Criteria andHLessThan(Integer value) {
            addCriterion("h <", value, "h");
            return (Criteria) this;
        }

        public Criteria andHLessThanOrEqualTo(Integer value) {
            addCriterion("h <=", value, "h");
            return (Criteria) this;
        }

        public Criteria andHIn(List<Integer> values) {
            addCriterion("h in", values, "h");
            return (Criteria) this;
        }

        public Criteria andHNotIn(List<Integer> values) {
            addCriterion("h not in", values, "h");
            return (Criteria) this;
        }

        public Criteria andHBetween(Integer value1, Integer value2) {
            addCriterion("h between", value1, value2, "h");
            return (Criteria) this;
        }

        public Criteria andHNotBetween(Integer value1, Integer value2) {
            addCriterion("h not between", value1, value2, "h");
            return (Criteria) this;
        }

        public Criteria andW2IsNull() {
            addCriterion("w2 is null");
            return (Criteria) this;
        }

        public Criteria andW2IsNotNull() {
            addCriterion("w2 is not null");
            return (Criteria) this;
        }

        public Criteria andW2EqualTo(Integer value) {
            addCriterion("w2 =", value, "w2");
            return (Criteria) this;
        }

        public Criteria andW2NotEqualTo(Integer value) {
            addCriterion("w2 <>", value, "w2");
            return (Criteria) this;
        }

        public Criteria andW2GreaterThan(Integer value) {
            addCriterion("w2 >", value, "w2");
            return (Criteria) this;
        }

        public Criteria andW2GreaterThanOrEqualTo(Integer value) {
            addCriterion("w2 >=", value, "w2");
            return (Criteria) this;
        }

        public Criteria andW2LessThan(Integer value) {
            addCriterion("w2 <", value, "w2");
            return (Criteria) this;
        }

        public Criteria andW2LessThanOrEqualTo(Integer value) {
            addCriterion("w2 <=", value, "w2");
            return (Criteria) this;
        }

        public Criteria andW2In(List<Integer> values) {
            addCriterion("w2 in", values, "w2");
            return (Criteria) this;
        }

        public Criteria andW2NotIn(List<Integer> values) {
            addCriterion("w2 not in", values, "w2");
            return (Criteria) this;
        }

        public Criteria andW2Between(Integer value1, Integer value2) {
            addCriterion("w2 between", value1, value2, "w2");
            return (Criteria) this;
        }

        public Criteria andW2NotBetween(Integer value1, Integer value2) {
            addCriterion("w2 not between", value1, value2, "w2");
            return (Criteria) this;
        }

        public Criteria andH2IsNull() {
            addCriterion("h2 is null");
            return (Criteria) this;
        }

        public Criteria andH2IsNotNull() {
            addCriterion("h2 is not null");
            return (Criteria) this;
        }

        public Criteria andH2EqualTo(Integer value) {
            addCriterion("h2 =", value, "h2");
            return (Criteria) this;
        }

        public Criteria andH2NotEqualTo(Integer value) {
            addCriterion("h2 <>", value, "h2");
            return (Criteria) this;
        }

        public Criteria andH2GreaterThan(Integer value) {
            addCriterion("h2 >", value, "h2");
            return (Criteria) this;
        }

        public Criteria andH2GreaterThanOrEqualTo(Integer value) {
            addCriterion("h2 >=", value, "h2");
            return (Criteria) this;
        }

        public Criteria andH2LessThan(Integer value) {
            addCriterion("h2 <", value, "h2");
            return (Criteria) this;
        }

        public Criteria andH2LessThanOrEqualTo(Integer value) {
            addCriterion("h2 <=", value, "h2");
            return (Criteria) this;
        }

        public Criteria andH2In(List<Integer> values) {
            addCriterion("h2 in", values, "h2");
            return (Criteria) this;
        }

        public Criteria andH2NotIn(List<Integer> values) {
            addCriterion("h2 not in", values, "h2");
            return (Criteria) this;
        }

        public Criteria andH2Between(Integer value1, Integer value2) {
            addCriterion("h2 between", value1, value2, "h2");
            return (Criteria) this;
        }

        public Criteria andH2NotBetween(Integer value1, Integer value2) {
            addCriterion("h2 not between", value1, value2, "h2");
            return (Criteria) this;
        }

        public Criteria andCfocusIsNull() {
            addCriterion("cfocus is null");
            return (Criteria) this;
        }

        public Criteria andCfocusIsNotNull() {
            addCriterion("cfocus is not null");
            return (Criteria) this;
        }

        public Criteria andCfocusEqualTo(String value) {
            addCriterion("cfocus =", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusNotEqualTo(String value) {
            addCriterion("cfocus <>", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusGreaterThan(String value) {
            addCriterion("cfocus >", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusGreaterThanOrEqualTo(String value) {
            addCriterion("cfocus >=", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusLessThan(String value) {
            addCriterion("cfocus <", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusLessThanOrEqualTo(String value) {
            addCriterion("cfocus <=", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusLike(String value) {
            addCriterion("cfocus like", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusNotLike(String value) {
            addCriterion("cfocus not like", value, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusIn(List<String> values) {
            addCriterion("cfocus in", values, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusNotIn(List<String> values) {
            addCriterion("cfocus not in", values, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusBetween(String value1, String value2) {
            addCriterion("cfocus between", value1, value2, "cfocus");
            return (Criteria) this;
        }

        public Criteria andCfocusNotBetween(String value1, String value2) {
            addCriterion("cfocus not between", value1, value2, "cfocus");
            return (Criteria) this;
        }

        public Criteria andPicIsNull() {
            addCriterion("pic is null");
            return (Criteria) this;
        }

        public Criteria andPicIsNotNull() {
            addCriterion("pic is not null");
            return (Criteria) this;
        }

        public Criteria andPicEqualTo(String value) {
            addCriterion("pic =", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotEqualTo(String value) {
            addCriterion("pic <>", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicGreaterThan(String value) {
            addCriterion("pic >", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicGreaterThanOrEqualTo(String value) {
            addCriterion("pic >=", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLessThan(String value) {
            addCriterion("pic <", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLessThanOrEqualTo(String value) {
            addCriterion("pic <=", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLike(String value) {
            addCriterion("pic like", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotLike(String value) {
            addCriterion("pic not like", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicIn(List<String> values) {
            addCriterion("pic in", values, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotIn(List<String> values) {
            addCriterion("pic not in", values, "pic");
            return (Criteria) this;
        }

        public Criteria andPicBetween(String value1, String value2) {
            addCriterion("pic between", value1, value2, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotBetween(String value1, String value2) {
            addCriterion("pic not between", value1, value2, "pic");
            return (Criteria) this;
        }

        public Criteria andCbackIsNull() {
            addCriterion("cback is null");
            return (Criteria) this;
        }

        public Criteria andCbackIsNotNull() {
            addCriterion("cback is not null");
            return (Criteria) this;
        }

        public Criteria andCbackEqualTo(Integer value) {
            addCriterion("cback =", value, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackNotEqualTo(Integer value) {
            addCriterion("cback <>", value, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackGreaterThan(Integer value) {
            addCriterion("cback >", value, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackGreaterThanOrEqualTo(Integer value) {
            addCriterion("cback >=", value, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackLessThan(Integer value) {
            addCriterion("cback <", value, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackLessThanOrEqualTo(Integer value) {
            addCriterion("cback <=", value, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackIn(List<Integer> values) {
            addCriterion("cback in", values, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackNotIn(List<Integer> values) {
            addCriterion("cback not in", values, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackBetween(Integer value1, Integer value2) {
            addCriterion("cback between", value1, value2, "cback");
            return (Criteria) this;
        }

        public Criteria andCbackNotBetween(Integer value1, Integer value2) {
            addCriterion("cback not between", value1, value2, "cback");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeIsNull() {
            addCriterion("onclick_type is null");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeIsNotNull() {
            addCriterion("onclick_type is not null");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeEqualTo(Integer value) {
            addCriterion("onclick_type =", value, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeNotEqualTo(Integer value) {
            addCriterion("onclick_type <>", value, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeGreaterThan(Integer value) {
            addCriterion("onclick_type >", value, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("onclick_type >=", value, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeLessThan(Integer value) {
            addCriterion("onclick_type <", value, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeLessThanOrEqualTo(Integer value) {
            addCriterion("onclick_type <=", value, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeIn(List<Integer> values) {
            addCriterion("onclick_type in", values, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeNotIn(List<Integer> values) {
            addCriterion("onclick_type not in", values, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeBetween(Integer value1, Integer value2) {
            addCriterion("onclick_type between", value1, value2, "onclickType");
            return (Criteria) this;
        }

        public Criteria andOnclickTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("onclick_type not between", value1, value2, "onclickType");
            return (Criteria) this;
        }

        public Criteria andCurlIsNull() {
            addCriterion("curl is null");
            return (Criteria) this;
        }

        public Criteria andCurlIsNotNull() {
            addCriterion("curl is not null");
            return (Criteria) this;
        }

        public Criteria andCurlEqualTo(String value) {
            addCriterion("curl =", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlNotEqualTo(String value) {
            addCriterion("curl <>", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlGreaterThan(String value) {
            addCriterion("curl >", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlGreaterThanOrEqualTo(String value) {
            addCriterion("curl >=", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlLessThan(String value) {
            addCriterion("curl <", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlLessThanOrEqualTo(String value) {
            addCriterion("curl <=", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlLike(String value) {
            addCriterion("curl like", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlNotLike(String value) {
            addCriterion("curl not like", value, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlIn(List<String> values) {
            addCriterion("curl in", values, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlNotIn(List<String> values) {
            addCriterion("curl not in", values, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlBetween(String value1, String value2) {
            addCriterion("curl between", value1, value2, "curl");
            return (Criteria) this;
        }

        public Criteria andCurlNotBetween(String value1, String value2) {
            addCriterion("curl not between", value1, value2, "curl");
            return (Criteria) this;
        }

        public Criteria andP1IsNull() {
            addCriterion("p1 is null");
            return (Criteria) this;
        }

        public Criteria andP1IsNotNull() {
            addCriterion("p1 is not null");
            return (Criteria) this;
        }

        public Criteria andP1EqualTo(String value) {
            addCriterion("p1 =", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1NotEqualTo(String value) {
            addCriterion("p1 <>", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1GreaterThan(String value) {
            addCriterion("p1 >", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1GreaterThanOrEqualTo(String value) {
            addCriterion("p1 >=", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1LessThan(String value) {
            addCriterion("p1 <", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1LessThanOrEqualTo(String value) {
            addCriterion("p1 <=", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1Like(String value) {
            addCriterion("p1 like", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1NotLike(String value) {
            addCriterion("p1 not like", value, "p1");
            return (Criteria) this;
        }

        public Criteria andP1In(List<String> values) {
            addCriterion("p1 in", values, "p1");
            return (Criteria) this;
        }

        public Criteria andP1NotIn(List<String> values) {
            addCriterion("p1 not in", values, "p1");
            return (Criteria) this;
        }

        public Criteria andP1Between(String value1, String value2) {
            addCriterion("p1 between", value1, value2, "p1");
            return (Criteria) this;
        }

        public Criteria andP1NotBetween(String value1, String value2) {
            addCriterion("p1 not between", value1, value2, "p1");
            return (Criteria) this;
        }

        public Criteria andP2IsNull() {
            addCriterion("p2 is null");
            return (Criteria) this;
        }

        public Criteria andP2IsNotNull() {
            addCriterion("p2 is not null");
            return (Criteria) this;
        }

        public Criteria andP2EqualTo(String value) {
            addCriterion("p2 =", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2NotEqualTo(String value) {
            addCriterion("p2 <>", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2GreaterThan(String value) {
            addCriterion("p2 >", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2GreaterThanOrEqualTo(String value) {
            addCriterion("p2 >=", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2LessThan(String value) {
            addCriterion("p2 <", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2LessThanOrEqualTo(String value) {
            addCriterion("p2 <=", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2Like(String value) {
            addCriterion("p2 like", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2NotLike(String value) {
            addCriterion("p2 not like", value, "p2");
            return (Criteria) this;
        }

        public Criteria andP2In(List<String> values) {
            addCriterion("p2 in", values, "p2");
            return (Criteria) this;
        }

        public Criteria andP2NotIn(List<String> values) {
            addCriterion("p2 not in", values, "p2");
            return (Criteria) this;
        }

        public Criteria andP2Between(String value1, String value2) {
            addCriterion("p2 between", value1, value2, "p2");
            return (Criteria) this;
        }

        public Criteria andP2NotBetween(String value1, String value2) {
            addCriterion("p2 not between", value1, value2, "p2");
            return (Criteria) this;
        }

        public Criteria andP3IsNull() {
            addCriterion("p3 is null");
            return (Criteria) this;
        }

        public Criteria andP3IsNotNull() {
            addCriterion("p3 is not null");
            return (Criteria) this;
        }

        public Criteria andP3EqualTo(String value) {
            addCriterion("p3 =", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3NotEqualTo(String value) {
            addCriterion("p3 <>", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3GreaterThan(String value) {
            addCriterion("p3 >", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3GreaterThanOrEqualTo(String value) {
            addCriterion("p3 >=", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3LessThan(String value) {
            addCriterion("p3 <", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3LessThanOrEqualTo(String value) {
            addCriterion("p3 <=", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3Like(String value) {
            addCriterion("p3 like", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3NotLike(String value) {
            addCriterion("p3 not like", value, "p3");
            return (Criteria) this;
        }

        public Criteria andP3In(List<String> values) {
            addCriterion("p3 in", values, "p3");
            return (Criteria) this;
        }

        public Criteria andP3NotIn(List<String> values) {
            addCriterion("p3 not in", values, "p3");
            return (Criteria) this;
        }

        public Criteria andP3Between(String value1, String value2) {
            addCriterion("p3 between", value1, value2, "p3");
            return (Criteria) this;
        }

        public Criteria andP3NotBetween(String value1, String value2) {
            addCriterion("p3 not between", value1, value2, "p3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ui_pub
     *
     * @mbg.generated do_not_delete_during_merge Sun May 05 11:55:33 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ui_pub
     *
     * @mbg.generated Sun May 05 11:55:33 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}