package com.reco.generate.entity;

import java.util.Date;

public class UserPayVal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.id
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.ip
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.uid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.fee
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.paytime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.exptime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Date exptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.createtime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.purchase
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String purchase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.area
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.sid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.sname
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.platform
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_val.stat
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.id
     *
     * @return the value of user_pay_val.id
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.id
     *
     * @param id the value for user_pay_val.id
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.ip
     *
     * @return the value of user_pay_val.ip
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.ip
     *
     * @param ip the value for user_pay_val.ip
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.uid
     *
     * @return the value of user_pay_val.uid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.uid
     *
     * @param uid the value for user_pay_val.uid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.fee
     *
     * @return the value of user_pay_val.fee
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.fee
     *
     * @param fee the value for user_pay_val.fee
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.paytime
     *
     * @return the value of user_pay_val.paytime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.paytime
     *
     * @param paytime the value for user_pay_val.paytime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.exptime
     *
     * @return the value of user_pay_val.exptime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Date getExptime() {
        return exptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.exptime
     *
     * @param exptime the value for user_pay_val.exptime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setExptime(Date exptime) {
        this.exptime = exptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.createtime
     *
     * @return the value of user_pay_val.createtime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.createtime
     *
     * @param createtime the value for user_pay_val.createtime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.purchase
     *
     * @return the value of user_pay_val.purchase
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getPurchase() {
        return purchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.purchase
     *
     * @param purchase the value for user_pay_val.purchase
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setPurchase(String purchase) {
        this.purchase = purchase == null ? null : purchase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.area
     *
     * @return the value of user_pay_val.area
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.area
     *
     * @param area the value for user_pay_val.area
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.sid
     *
     * @return the value of user_pay_val.sid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.sid
     *
     * @param sid the value for user_pay_val.sid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.sname
     *
     * @return the value of user_pay_val.sname
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.sname
     *
     * @param sname the value for user_pay_val.sname
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.platform
     *
     * @return the value of user_pay_val.platform
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.platform
     *
     * @param platform the value for user_pay_val.platform
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_val.stat
     *
     * @return the value of user_pay_val.stat
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_val.stat
     *
     * @param stat the value for user_pay_val.stat
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}