package com.reco.generate.entity;

import java.util.Date;

public class UserPayInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.id
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.ip
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.uid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.fee
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.createtime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.purchase
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String purchase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.area
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.id_content
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer idContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.content
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.detail
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pay_info.platform
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    private Integer platform;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.id
     *
     * @return the value of user_pay_info.id
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.id
     *
     * @param id the value for user_pay_info.id
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.ip
     *
     * @return the value of user_pay_info.ip
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.ip
     *
     * @param ip the value for user_pay_info.ip
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.uid
     *
     * @return the value of user_pay_info.uid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.uid
     *
     * @param uid the value for user_pay_info.uid
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.fee
     *
     * @return the value of user_pay_info.fee
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.fee
     *
     * @param fee the value for user_pay_info.fee
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.createtime
     *
     * @return the value of user_pay_info.createtime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.createtime
     *
     * @param createtime the value for user_pay_info.createtime
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.purchase
     *
     * @return the value of user_pay_info.purchase
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getPurchase() {
        return purchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.purchase
     *
     * @param purchase the value for user_pay_info.purchase
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setPurchase(String purchase) {
        this.purchase = purchase == null ? null : purchase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.area
     *
     * @return the value of user_pay_info.area
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.area
     *
     * @param area the value for user_pay_info.area
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.id_content
     *
     * @return the value of user_pay_info.id_content
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getIdContent() {
        return idContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.id_content
     *
     * @param idContent the value for user_pay_info.id_content
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setIdContent(Integer idContent) {
        this.idContent = idContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.content
     *
     * @return the value of user_pay_info.content
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.content
     *
     * @param content the value for user_pay_info.content
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.detail
     *
     * @return the value of user_pay_info.detail
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.detail
     *
     * @param detail the value for user_pay_info.detail
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pay_info.platform
     *
     * @return the value of user_pay_info.platform
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pay_info.platform
     *
     * @param platform the value for user_pay_info.platform
     *
     * @mbg.generated Fri May 31 10:52:59 CST 2019
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }
}